# mkdocs.yml
site_name: Le Lieu-Dit
site_description: Page accessibilité du Lieu-Dit
site_url: ""
use_directory_urls: false

extra_css:
  - stylesheets/extra.css

theme: 
  name: material
  language: fr
  favicon: assets/logo/Lieu-dit-noir.png
  logo: assets/logo/Lieu-dit-noir.png
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    #- toc.integrate 
  palette:
    primary: custom

nav:
  - C'est quoi ?: index.md
  - <span class="lsf braille">C'est quoi ? LSF</span>: index-lsf.md 
  - Accessibilité: 
    - Fiche Accessibilité: access.md
    - <span class="lsf">Fiche Accessibilité LSF</span>: access-lsf.md 
    - Où trouver la fiche ?: access-infos.md
    - Photographies: photos.md
    - Travail en cours: todo.md
    - Pour les orgas: 
      - ressources.md
      - Ressources:
        - orgas/dispositifs.md
        - orgas/accueillir-dv.md
        - orgas/materiel.md
  - Programme:
    - En papier et braille: prog-infos.md
    - A télécharger: prog.md
    - <span class="lsf">Programme LSF</span>: prog-lsf.md
    - Sur le site internet "Pommes de Lune": https://pommesdelune.fr/place/2-le-lieu-dit
  - À propos: about.md

#markdown_extensions:
  #- toc:
    #- toc_depth: 2

plugins:
  - search
  - print-site

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
