# mkdocs.yml
site_name: Lieu-Dit
site_description: Page accessibilité du Lieu-Dit

extra_css:
  - stylesheets/extra.css

theme: 
  name: material
  language: fr
  icon:
    logo: material/human
  #favicon: images/favicon.png
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    #- toc.integrate 
  palette:
    primary: custom

nav:
  - Accessibilité: 
    - <span class="lsf">Vidéo LSF</span>: lsf.md 
    - Fiche Accessibilité: index.md
    - Où trouver la fiche ?: infos.md
  - Pour les orgas: 
    - ressources.md
    - Ressources:
      - orgas/dispositifs.md
      - orgas/accueillir_dv.md
      - orgas/materiel.md
  - Travail en cours:
    - En discussion: todo.md
    - À propos: about.md
  - Évenements:
    - <span class="lsf">Programmes LSF</span>: programme_lsf.md
    - Agenda Pommes de Lune: https://pommesdelune.fr/place/2-le-lieu-dit

#markdown_extensions:
  #- toc:
    #- toc_depth: 2

plugins:
  - search
  - print-site
